apiVersion: apps/v1
kind: Deployment
metadata:
  name: eric-opt-deployment-30b
spec:
  selector:
    matchLabels:
      app: eric-take-home-trial
  replicas: 1
  template:
    metadata:
      labels:
        app: eric-take-home-trial
    spec:
      containers:
      - name: eric-opt-30b 
        image: erichen0615/opt-30b-v1
        imagePullPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu.nvidia.com/class
                operator: In
                values:
                  - A40